[package]
name = "program1-module-order"
version.workspace = true
edition.workspace = true

[dependencies]
program1-contracts = { path = "../../contracts" }
async-trait.workspace = true
tokio.workspace = true
serde.workspace = true
uuid.workspace = true
chrono.workspace = true
tracing.workspace = true

[dev-dependencies]
program1-module-user = { path = "../user" }
program1-module-product = { path = "../product" }
