[package]
name = "program1-module-buyer"
version.workspace = true
edition.workspace = true

[dependencies]
program1-contracts = { path = "../../contracts" }
program1-core = { path = "../../core" }
async-trait.workspace = true
tokio.workspace = true
serde.workspace = true
uuid.workspace = true
chrono.workspace = true
tracing.workspace = true
serde_json.workspace = true
sqlx = { workspace = true }
rand = { workspace = true }
argon2 = { workspace = true }
reqwest = { version = "0.12", default-features = false, features = ["json"] }

[dev-dependencies]
program1-module-auth = { path = "../auth" }
program1-module-audit = { path = "../audit" }
